[package]
name = "pbjson-build"
version = "0.1.0"
authors = ["Raphael Taylor-Davies <r.taylordavies@googlemail.com>"]
edition = "2018"
description = "Generates Serialize and Deserialize implementations for prost message types"
license = "MIT"
keywords = ["protobuf", "json", "serde"]
categories = ["encoding"]
repository = "https://github.com/influxdata/pbjson"

[dependencies]

heck = "0.3"
prost = "0.9"
prost-types = "0.9"
itertools = "0.10"

[dev-dependencies]
tempfile = "3.1"
